name: Hello World

on: [push]  # 触发条件：代码推送时运行

jobs:
  say-hello:
    runs-on: ubuntu-latest  # 使用最新 Ubuntu 运行环境
    
    steps:
      - name: Print Hello World
        run: echo "Hello World"  # 输出 Hello World
