name: Read and Display File

on: [push]  # 触发条件：代码推送时运行（与原图一致）

jobs:
  display-file:
    runs-on: ubuntu-latest  # 使用最新Ubuntu环境（与原图一致）
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 必须先检出代码才能访问文件
        
      - name: Display test.txt
        run: |
          if [ -f "doc/test.txt" ]; then
            echo "文件内容："
            cat doc/test.txt  # 输出文件内容
          else
            echo "::error::文件 doc/test.txt 不存在"
            exit 1  # 如果文件不存在则报错退出
          fi
