- name: Validate test file
  run: |
    # 改为递归查找测试文件
    TEST_FILE=$(find src/test/java -name "*Test.java" | head -n 1)
    if [ -z "$TEST_FILE" ]; then
      echo "::error::No test file found in src/test/java/"
      exit 1
    else
      echo "Found test file: $TEST_FILE"
      javac $TEST_FILE
    fi
