name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # 只在main分支推送时触发
  pull_request:
    branches: [ "main" ]  # PR合并到main时也触发

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 官方Action获取代码

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml  # 跳过测试可加 -DskipTests

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: target-package
        path: target/*.jar  # 保存生成的jar包

  deploy:
    needs: build-and-test  # 依赖构建任务
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # 额外安全限制
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: target-package

    - name: List files (debug)
      run: ls -R  # 查看文件结构（调试用）

    - name: Deploy to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEPLOY_HOST }}  # 服务器IP
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "*.jar"
        target: "/opt/myapp"
        strip_components: 1

    - name: Restart Service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl stop myapp.service
          nohup java -jar /opt/myapp/*.jar > /var/log/myapp.log 2>&1 &
