name: CI Pipeline  # 工作流名称
on: [push]        # 触发事件：代码推送时自动运行

jobs:
  build-and-test:  # 任务名称
    runs-on: ubuntu-latest  # 使用最新版 Ubuntu 系统
    steps:
      # 1. 拉取代码到 Runner
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境（示例）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x  # 指定 Node 版本

      # 3. 安装依赖 & 运行测试（按需修改）
      - name: Install dependencies
        run: npm ci           # 更安全的依赖安装

      - name: Run tests
        run: npm test         # 执行测试命令
