name: Safe Auto-Merge

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  merge-on-pr-close:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge --no-ff main
          git push origin ${{ github.event.pull_request.head.ref }}
