name: Auto-Merge to Main

on:
  push:
    branches-ignore: 
      - 'main'  # 排除main分支本身的推送

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    # 必须添加权限声明
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整git历史

      - name: Merge to main
        run: |
          # 设置git身份
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 尝试合并（使用--no-ff保留合并提交）
          git fetch origin main
          git checkout main
          git merge --no-ff ${{ github.ref_name }} -m "Auto-merge from ${{ github.ref_name }}"
          
          # 处理可能的冲突
          if git push origin main; then
            echo "Merge succeeded"
          else
            echo "::error::Merge conflict detected"
            exit 1
          fi
